services:
  - type: web
    name: champion-winner-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 8000
      - key: MODEL_PATH
        value: ./models/
      - key: DATA_PATH
        value: ./data/ 